import sys

#Multiples of 3 and 5
"""
If we list all the natural numbers below 10 that are multiples of 3 or 5,
we get 3, 5, 6 and 9. The sum of these multiples is 23.
Find the sum of all the multiples of 3 or 5 below 1000.
"""
def multThreeOrFive():
	sum = 0
	for i in range(0, 1000):
		if((i%5 == 0) or (i%3 == 0)): # check if muliple of 3 or 5 
			sum += i  # if so add value to sum
	return sum

#Even Fibonacci Numbers
"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""
def fib(n):				#recursive defining fibonacci sequence
	if(n == 0):
		return 0
	elif(n <= 2):
		return 1
	else:
		return fib(n-1) + fib(n-2)


def evenFibonacciSum():
	sum = 0
	i = 0
	while True: # go thru sequence
		if(fib(i) >= 4000000):  # break if sequence reach 4mil
			break
		elif(fib(i)%2 == 0):	#if even add to rolling sum
			sum += fib(i)
		i += 1 #i++
	return sum




#//////////////////////Write Under Here//////////////////////////////////////
print("Answer:")
print(evenFibonacciSum())  # enter method from problem set

sys.exit()
